### ISSUE TITLE
Document Glossarist YAML v2 format using YAML Schema

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/concept-model#27]
From https://github.com/glossarist/glossarist-ruby/issues/76#issuecomment-1670487906

We need to document the Glossarist YAML v2 format in this repository using YAML/JSON Schema.

**Comment by HassanAkbar** [comment]
@ronaldtse I am not sure about the structure of glossarist v2 format. To better understand what it is I was looking at [metaversestandards-glossary](https://github.com/MetaverseStandards/metaversestandards-glossary) and I have a few questions related to it.

- From what I understand in V2 we removed the localizations from the concept files and moved them to their respective files and assigned an `ID`, other than that the keys and structure is almost same. Is this correct or are there some structural changes as well that I have missed?

- I noticed that the keys are in camel casing e.g [concept/01fa30d3-4e4b-4142-b68a-c299b55b3fb8](https://github.com/MetaverseStandards/metaversestandards-glossary/blob/main/msfglossary/concept/01fa30d3-4e4b-4142-b68a-c299b55b3fb8.yaml)

    ```yaml
    id: 01fa30d3-4e4b-4142-b68a-c299b55b3fb8
    data:
      identifier: '88'
      localizedConcepts:
        eng: 2b959537-c600-41d1-aeb7-7233c35d30eb
    status: valid
    dateAccepted: 2023-08-04T11:33:09.535Z
    ```
    do we need to support `camel case` or `snake case` or both in glossarist?

**Comment by ronaldtse** [comment]
> From what I understand in V2 we removed the localizations from the concept files and moved them to their respective files [...]

Removed from the files and moved them to "their respective files"? What did you mean?

> do we need to support camel case or snake case or both in glossarist?

I actually prefer snake case for YAML keys. @ribose-jeffreylau @strogonoff are you okay with this?

**Comment by HassanAkbar** [comment]
> Removed from the files and moved them to "their respective files"? What did you mean?

@ronaldtse I mean like in the example below, everything under the `data` is from current glossarist model, just moved to a separate `localized-concept` file with a `uuid` and in the `concept` file we are adding a reference to this file.

```yaml
id: 00250c70-121c-40d3-8230-8b87380dd1ae
data:
  language_code: eng
  terms:
    - normative_status: preferred
      type: expression
      designation: time
  definition:
    - content: monotonically increasing value generated by a node
  notes: []
  examples: []
  authoritativeSource:
    - link: >-
        https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-IS.proof/Part01/glossary.html#Time
status: valid
dateAccepted: 2023-08-04T11:33:09.535Z
```
